apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mannazu-redis
  namespace: mannazu
spec:
  serviceName: mannazu-redis-service
  replicas: 1
  selector:
    matchLabels:
      app: mannazu-redis
  template:
    metadata:
      labels:
        app: mannazu-redis
    spec:
      containers:
        - name: mannazu-redis
          image: redis:alpine
          ports:
            - containerPort: 6379
              name: redis
          volumeMounts:
            - name: redis-data
              mountPath: /data
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
            limits:
              memory: "500Mi"
              cpu: "512m"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: mannazu-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mannazu-redis-service
  namespace: mannazu
spec:
  selector:
    app: mannazu-redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: LoadBalancer