apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mannazu-mysql
  namespace: mannazu
spec:
  serviceName: mannazu-mysql-service
  replicas: 1
  selector:
    matchLabels:
      app: mannazu-mysql
  template:
    metadata:
      labels:
        app: mannazu-mysql
    spec:
      containers:
        - name: mannazu-mysql
          image: yobasystems/alpine-mariadb:10.5.9
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: mysql-password
            - name: MARIADB_CHARACTER_SET_SERVER
              value: "utf8mb4"
            - name: MARIADB_COLLATION_SERVER
              value: "utf8mb4_unicode_ci"                  
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
            - name: init-script 
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
            # - name: mysql-config
            #   mountPath: /etc/mysql/conf.d/custom.cnf
            #   subPath: custom.cnf            
          resources:
            requests:
              memory: "0Mi"  
              cpu: "0m"      
            limits:
              memory: "500Mi"    
              cpu: "512m"             
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mannazu-mysql-pvc
        - name: init-script
          configMap:
            name: db-init-script
        # - name: mysql-config
        #   configMap:
        #     name: mysql-custom-config
        #     items:
        #     - key: custom.cnf
        #       path: custom.cnf            
---
apiVersion: v1
kind: Service
metadata:
  name: mannazu-mysql-service
  namespace: mannazu
spec:
  selector:
    app: mannazu-mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: LoadBalancer
