spring:
  application:
    name: gateway-server
  profiles:
    active: prod
  config:
    import: "optional:configserver:http://nyamnyam-config-server-e8b23-100122224-c82fb374a3f0.kr.lb.naverncp.com:8888"