apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: swagger-service-hpa-canary
  namespace: mannazu
spec:
  scaleTargetRef: 
    apiVersion: apps/v1
    kind: Deployment
    name: swagger-service-canary
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
