apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auth-service-hpa
  namespace: mannazu
spec:
  scaleTargetRef: 
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    name: auth-service
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
